# Site
repository: r1990v/r1990v.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rahul Vats
title: Senior Performance Engineer
email: r1990v@gmail.com
website: https://r1990v.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: r1990v
github_username:  r1990v
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rahulvats90
linkedin_username: rahulvats1990
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: RahulVats90
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rahul and I'm a senior performance engineer. As a passionate software engineer with a goal-oriented mindset, I have dedicated 8 years of my career to mastering the art of performance, automation, and security testing. My expertise lies in using tools such as JMeter, LoadRunner, Neoload, Selenium, IBM Appscan, Blackduck, MobSf, and Burp Suite to ensure that every product I work on meets the highest standards of quality.

  I am most skilled in: <mark>Performance Engieering</mark> and <mark>Playing Badminton</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amity University
        caption: 2012 - 2015
        sub_title:  Master of Computer Application
        quote: >
          Amity School of Engineering and Technology (ASET), Amity University Uttar Pradesh is one of the pioneer institutions in the field of Engineering, Research and Technology and has been ranked 4th in North Zone by Times Of India (Education Times)
        description: | # this will include new lines to allow paragraphs
          During my time at Amity University I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time at the university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Amity Conference and Research* taking on roles such as *Registration Coordinator* and *Session Modrator*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gaming (Fav: Ghost of Tsushima)
      - Movies (Fav: Life of Pi)
      - Cooking (Fav: Chinese Food)
      - Eating (Fav: Natti Biryani)
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
